* Bullseye

** Overview
   Bullseye is a smart shelf system that suggests products depending on preferences.
   Customer fills in a questionnaire consisting of single choice questions and
   submits their choices. Then application lights up shelf with the best matching
   product based on given answers to visually indicate which products to pick up
   and presents overall result on the screen.

   Bullseye consists of two parts:
   - backend (server)
   - frontend (client)
   - Raspberry PI client (for controlling shelves)
   - hardware (used on each shelf individually)
   - set of shelves with lights connected to Raspberry Pi
     
   Bullseye communicates with RPI using MQTT protocol which is not included in this project.

** Prerequisites
   - Kyma cluster for deployment
   - MQTT server for communication with hardware
   - Raspberry PI with ~bullseye-rpi~ client deployed
   - Shelves with ~slab.ino~ flashed, connected to RPI physically
   - SAP Commerce Cloud instance with Omni Commerce Connect extension

** Installation
   Refer to [[./docs/installation.org][this]] document.
   
** Configuration
   Refer to [[./docs/configuration.org][this]] document.

** Usage
   [[./docs/assets/diagram_bullseye.svg]]

   Frontend side of application presents questionnaire which consists of single choice questions.
   After submitting answers a list of available products, sorted descending by matching score
   is being presented to a suer. The best matching product is exposed on a top of a site.
   A shelf with the chosen product is being light up to indicate what should be picked by the user.
   For more details refer to [[.frontend/README.md][this]] document.


   Backend side is for an administrator to adjust questions, answers, products and
   mappings between them. For more details refer to [[.backend/docs/configuration.org][this]] document.



** Development
   1. Close this repository.
   2. Create a new branch on base of `develop`.
   3. Make appropriate changes.
   4. Open pull request and include all details in description in terms of what has been changed
      and what was the reason behind changes.
