// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

import stands "github.com/kyma-incubator/bullseye-showcase/backend/internal/db/stands"

// StandsRepository is an autogenerated mock type for the StandsRepository type
type StandsRepository struct {
	mock.Mock
}

// GetAllStands provides a mock function with given fields:
func (_m *StandsRepository) GetAllStands() ([]stands.StandDTO, error) {
	ret := _m.Called()

	var r0 []stands.StandDTO
	if rf, ok := ret.Get(0).(func() []stands.StandDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]stands.StandDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
